(define (problem destroy-obstacle)
  (:domain world-of-tanks)
  (:init
    (at tank1 location1)
    (obstacle-at obstacle1 location2)
    (adjacent location1 location2)
    (adjacent location2 location1)
    (clear location1)
    (loaded tank1 shell1)
    (can-shoot tank1 obstacle1 location1)
    (obstacle-at obstacle1 location2)
  )
  (:goal (not (obstacle-at obstacle1 location2)))
)
