(define (problem deliver-packages)
  (:domain delivery)
  (:init
    (at truck1 location1)
    (at package1 location1)
    (at package2 location2)
    (available truck1)
    (destination package1 location2)
    (destination package2 location3)
  )
  (:goal (and (at package1 location2) (at package2 location3)))
)
